#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#Using module
' a test module '

__author__ = 'Michael Liao'

import sys

def test():
    args = sys.argv
    if len(args) == 1:
        print('Hello, world!')
    elif len(args) == 2:
        print('Hello, %s!' % arg[1])
    else:
        print('Too many arguments!')

if __name__ == '_main_':
    test()
#End of using module

